---
title: "hw5_jl6521"
author: "Jiayi"
date: "2024-11-10"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

## Problem1
```{r birthday problem}
birthday = function(group_size) {
  day = sample(1:365, group_size, replace = TRUE)
  return(length(day)!= length(unique(day)))
}

group_sizes = 2:50
results = tibble(group_size = group_sizes, prob = NA)
for (i in seq_along(group_sizes)) {
  same_birth = sum(replicate(10000,birthday(group_sizes[i])))
  prob <- same_birth / 10000
  results$prob[i] <- prob
}

print(results)

ggplot(results, aes(x = group_size, y = prob)) +
  geom_line() +
  geom_point() +
  labs(x = "group size", y = "probability of shared birthday",
       title = "Probability of shared birthday with group size") +
  theme_minimal()
```
Comment: from the graph, we can see that as group size increases (closer to 50), the probability of duplicated birthday in the group increases. Eventually as the group size be closer to 50, the probability is closer to 1.

